#ifndef NAEMON_BUILDOPTS_H__
#define NAEMON_BUILDOPTS_H__
#define NAEMON_SYSCONFDIR "@@NAEMON_SYSCONFDIR@@"
#define NAEMON_LOCALSTATEDIR "@@NAEMON_LOCALSTATEDIR@@"
#define NAEMON_LOGDIR "@@NAEMON_LOGDIR@@"
#define NAEMON_LOCKFILE "@@NAEMON_LOCKFILE@@"
#define NAEMON_GROUP "@@NAEMON_GROUP@@"
#define NAEMON_USER "@@NAEMON_USER@@"
#endif
