#include "config.h"
#include "common.h"
#include "defaults.h"
#include "statusdata.h"
#include "comments.h"
#include "downtime.h"
#include "macros.h"
#include "xsddefault.h"
#include "utils.h"
#include "logging.h"
#include "globals.h"
#include "nm_alloc.h"
#include "nm_writebuf.h"
#include <string.h>
#include <unistd.h>
#include <errno.h>

int buffer_stats[1][3];
int program_stats[MAX_CHECK_STATS_TYPES][3];

/******************************************************************/
/********************* INIT/CLEANUP FUNCTIONS *********************/
/******************************************************************/

/* initialize status data */
int xsddefault_initialize_status_data(const char *cfgfile)
{
	nagios_macros *mac;

	/* initialize locations if necessary */
	if (!status_file)
		status_file = nm_strdup(get_default_status_file());

	/* make sure we have what we need */
	if (status_file == NULL)
		return ERROR;

	mac = get_global_macros();
	/* save the status file macro */
	nm_free(mac->x[MACRO_STATUSDATAFILE]);
	mac->x[MACRO_STATUSDATAFILE] = nm_strdup(status_file);
	strip(mac->x[MACRO_STATUSDATAFILE]);

	/* delete the old status log (it might not exist) */
	if (status_file)
		unlink(status_file);

	return OK;
}


/* cleanup status data before terminating */
int xsddefault_cleanup_status_data(int delete_status_data)
{
	int return_code = OK;

	/* delete the status log */
	if (delete_status_data == TRUE && status_file) {
		if (unlink(status_file))
			return_code = ERROR;
	}

	nm_free(status_file);

	return return_code;
}


/******************************************************************/
/****************** STATUS DATA OUTPUT FUNCTIONS ******************/
/******************************************************************/

/* write all status data to file */
/* status.dat indents every field inside a block with a tab */
#define sd_kv_str(wb, key, val)      nm_wb_kv_str((wb), "\t" key, (val))
#define sd_kv_int(wb, key, val)      nm_wb_kv_int((wb), "\t" key, (val))
#define sd_kv_uint(wb, key, val)     nm_wb_kv_uint((wb), "\t" key, (val))
#define sd_kv_dbl(wb, key, fmt, val) nm_wb_kv_dbl((wb), "\t" key, (fmt), (val))

int xsddefault_save_status_data(void)
{
	char *tmp_log = NULL;
	customvariablesmember *temp_customvariablesmember = NULL;
	host *temp_host = NULL;
	service *temp_service = NULL;
	contact *temp_contact = NULL;
	comment *temp_comment = NULL;
	GHashTableIter iter;
	gpointer comment_;
	scheduled_downtime *temp_downtime = NULL;
	time_t current_time;
	int fd = 0;
	struct nm_writebuf wb;
	int result = OK;

	/* users may not want us to write status data */
	if (!status_file || !strcmp(status_file, "/dev/null"))
		return OK;

	nm_asprintf(&tmp_log, "%sXXXXXX", status_file);
	if (tmp_log == NULL)
		return ERROR;

	log_debug_info(DEBUGL_STATUSDATA, 2, "Writing status data to temp file '%s'\n", tmp_log);

	if ((fd = mkstemp(tmp_log)) == -1) {

		/* log an error */
		nm_log(NSLOG_RUNTIME_ERROR, "Error: Unable to create temp file '%s' for writing status data: %s\n", tmp_log, strerror(errno));

		nm_free(tmp_log);

		return ERROR;
	}

	nm_writebuf_init(&wb, fd, NM_WRITEBUF_SIZE);

	/* generate check statistics */
	generate_check_stats();

	/* write version info to status file */
	nm_wb_lit(&wb, "########################################\n");
	nm_wb_lit(&wb, "#          NAGIOS STATUS FILE\n");
	nm_wb_lit(&wb, "#\n");
	nm_wb_lit(&wb, "# THIS FILE IS AUTOMATICALLY GENERATED\n");
	nm_wb_lit(&wb, "# BY NAGIOS.  DO NOT MODIFY THIS FILE!\n");
	nm_wb_lit(&wb, "########################################\n\n");

	time(&current_time);

	/* write file info */
	nm_wb_lit(&wb, "info {\n");
	sd_kv_uint(&wb, "created", current_time);
	nm_wb_lit(&wb, "\tversion=" VERSION "\n");
	nm_wb_lit(&wb, "\t}\n\n");

	/* save program status data */
	nm_wb_lit(&wb, "programstatus {\n");
	sd_kv_uint(&wb, "modified_host_attributes", modified_host_process_attributes);
	sd_kv_uint(&wb, "modified_service_attributes", modified_service_process_attributes);
	sd_kv_int(&wb, "nagios_pid", nagios_pid);
	sd_kv_int(&wb, "daemon_mode", daemon_mode);
	sd_kv_uint(&wb, "program_start", program_start);
	sd_kv_uint(&wb, "last_log_rotation", last_log_rotation);
	sd_kv_int(&wb, "enable_notifications", enable_notifications);
	sd_kv_int(&wb, "active_service_checks_enabled", execute_service_checks);
	sd_kv_int(&wb, "passive_service_checks_enabled", accept_passive_service_checks);
	sd_kv_int(&wb, "active_host_checks_enabled", execute_host_checks);
	sd_kv_int(&wb, "passive_host_checks_enabled", accept_passive_host_checks);
	sd_kv_int(&wb, "enable_event_handlers", enable_event_handlers);
	sd_kv_int(&wb, "obsess_over_services", obsess_over_services);
	sd_kv_int(&wb, "obsess_over_hosts", obsess_over_hosts);
	sd_kv_int(&wb, "check_service_freshness", check_service_freshness);
	sd_kv_int(&wb, "check_host_freshness", check_host_freshness);
	sd_kv_int(&wb, "enable_flap_detection", enable_flap_detection);
	sd_kv_int(&wb, "process_performance_data", process_performance_data);
	sd_kv_str(&wb, "global_host_event_handler", global_host_event_handler);
	sd_kv_str(&wb, "global_service_event_handler", global_service_event_handler);
	sd_kv_str(&wb, "global_host_notification_handler", global_host_notification_handler);
	sd_kv_str(&wb, "global_service_notification_handler", global_service_notification_handler);
	sd_kv_uint(&wb, "next_comment_id", next_comment_id);
	sd_kv_uint(&wb, "next_downtime_id", next_downtime_id);
	sd_kv_uint(&wb, "next_event_id", next_event_id);
	nm_wb_printf(&wb, "\tactive_scheduled_host_check_stats=%d,%d,%d\n", check_statistics[ACTIVE_SCHEDULED_HOST_CHECK_STATS].minute_stats[0], check_statistics[ACTIVE_SCHEDULED_HOST_CHECK_STATS].minute_stats[1], check_statistics[ACTIVE_SCHEDULED_HOST_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\tactive_ondemand_host_check_stats=%d,%d,%d\n", check_statistics[ACTIVE_ONDEMAND_HOST_CHECK_STATS].minute_stats[0], check_statistics[ACTIVE_ONDEMAND_HOST_CHECK_STATS].minute_stats[1], check_statistics[ACTIVE_ONDEMAND_HOST_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\tpassive_host_check_stats=%d,%d,%d\n", check_statistics[PASSIVE_HOST_CHECK_STATS].minute_stats[0], check_statistics[PASSIVE_HOST_CHECK_STATS].minute_stats[1], check_statistics[PASSIVE_HOST_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\tactive_scheduled_service_check_stats=%d,%d,%d\n", check_statistics[ACTIVE_SCHEDULED_SERVICE_CHECK_STATS].minute_stats[0], check_statistics[ACTIVE_SCHEDULED_SERVICE_CHECK_STATS].minute_stats[1], check_statistics[ACTIVE_SCHEDULED_SERVICE_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\tactive_ondemand_service_check_stats=%d,%d,%d\n", check_statistics[ACTIVE_ONDEMAND_SERVICE_CHECK_STATS].minute_stats[0], check_statistics[ACTIVE_ONDEMAND_SERVICE_CHECK_STATS].minute_stats[1], check_statistics[ACTIVE_ONDEMAND_SERVICE_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\tpassive_service_check_stats=%d,%d,%d\n", check_statistics[PASSIVE_SERVICE_CHECK_STATS].minute_stats[0], check_statistics[PASSIVE_SERVICE_CHECK_STATS].minute_stats[1], check_statistics[PASSIVE_SERVICE_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\tcached_host_check_stats=%d,%d,%d\n", check_statistics[ACTIVE_CACHED_HOST_CHECK_STATS].minute_stats[0], check_statistics[ACTIVE_CACHED_HOST_CHECK_STATS].minute_stats[1], check_statistics[ACTIVE_CACHED_HOST_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\tcached_service_check_stats=%d,%d,%d\n", check_statistics[ACTIVE_CACHED_SERVICE_CHECK_STATS].minute_stats[0], check_statistics[ACTIVE_CACHED_SERVICE_CHECK_STATS].minute_stats[1], check_statistics[ACTIVE_CACHED_SERVICE_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\texternal_command_stats=%d,%d,%d\n", check_statistics[EXTERNAL_COMMAND_STATS].minute_stats[0], check_statistics[EXTERNAL_COMMAND_STATS].minute_stats[1], check_statistics[EXTERNAL_COMMAND_STATS].minute_stats[2]);

	nm_wb_printf(&wb, "\tparallel_host_check_stats=%d,%d,%d\n", check_statistics[PARALLEL_HOST_CHECK_STATS].minute_stats[0], check_statistics[PARALLEL_HOST_CHECK_STATS].minute_stats[1], check_statistics[PARALLEL_HOST_CHECK_STATS].minute_stats[2]);
	nm_wb_printf(&wb, "\tserial_host_check_stats=%d,%d,%d\n", check_statistics[SERIAL_HOST_CHECK_STATS].minute_stats[0], check_statistics[SERIAL_HOST_CHECK_STATS].minute_stats[1], check_statistics[SERIAL_HOST_CHECK_STATS].minute_stats[2]);
	nm_wb_lit(&wb, "\t}\n\n");


	/* save host status data */
	for (temp_host = host_list; temp_host != NULL; temp_host = temp_host->next) {

		nm_wb_lit(&wb, "hoststatus {\n");
		sd_kv_str(&wb, "host_name", temp_host->name);

		sd_kv_uint(&wb, "modified_attributes", temp_host->modified_attributes);
		sd_kv_str(&wb, "check_command", temp_host->check_command);
		sd_kv_str(&wb, "check_period", temp_host->check_period);
		sd_kv_str(&wb, "notification_period", temp_host->notification_period);
		sd_kv_dbl(&wb, "check_interval", "%f", temp_host->check_interval);
		sd_kv_dbl(&wb, "retry_interval", "%f", temp_host->retry_interval);
		sd_kv_str(&wb, "event_handler", temp_host->event_handler);

		sd_kv_int(&wb, "has_been_checked", temp_host->has_been_checked);
		sd_kv_dbl(&wb, "check_execution_time", "%.3f", temp_host->execution_time);
		sd_kv_dbl(&wb, "check_latency", "%.3f", temp_host->latency);
		sd_kv_int(&wb, "check_type", temp_host->check_type);
		sd_kv_int(&wb, "current_state", temp_host->current_state);
		sd_kv_int(&wb, "last_hard_state", temp_host->last_hard_state);
		sd_kv_uint(&wb, "last_event_id", temp_host->last_event_id);
		sd_kv_uint(&wb, "current_event_id", temp_host->current_event_id);
		sd_kv_str(&wb, "current_problem_id", temp_host->current_problem_id);
		sd_kv_str(&wb, "last_problem_id", temp_host->last_problem_id);
		sd_kv_uint(&wb, "problem_start", temp_host->problem_start);
		sd_kv_uint(&wb, "problem_end", temp_host->problem_end);
		sd_kv_str(&wb, "plugin_output", temp_host->plugin_output);
		sd_kv_str(&wb, "long_plugin_output", temp_host->long_plugin_output);
		sd_kv_str(&wb, "performance_data", temp_host->perf_data);
		sd_kv_uint(&wb, "last_check", temp_host->last_check);
		sd_kv_uint(&wb, "next_check", temp_host->next_check);
		sd_kv_int(&wb, "check_options", temp_host->check_options);
		sd_kv_int(&wb, "current_attempt", temp_host->current_attempt);
		sd_kv_int(&wb, "max_attempts", temp_host->max_attempts);
		sd_kv_int(&wb, "state_type", temp_host->state_type);
		sd_kv_uint(&wb, "last_state_change", temp_host->last_state_change);
		sd_kv_uint(&wb, "last_hard_state_change", temp_host->last_hard_state_change);
		sd_kv_uint(&wb, "last_time_up", temp_host->last_time_up);
		sd_kv_uint(&wb, "last_time_down", temp_host->last_time_down);
		sd_kv_uint(&wb, "last_time_unreachable", temp_host->last_time_unreachable);
		sd_kv_uint(&wb, "last_notification", temp_host->last_notification);
		sd_kv_uint(&wb, "next_notification", temp_host->next_notification);
		sd_kv_int(&wb, "no_more_notifications", temp_host->no_more_notifications);
		sd_kv_int(&wb, "current_notification_number", temp_host->current_notification_number);
		sd_kv_str(&wb, "current_notification_id", temp_host->current_notification_id);
		sd_kv_int(&wb, "notifications_enabled", temp_host->notifications_enabled);
		sd_kv_int(&wb, "problem_has_been_acknowledged", temp_host->problem_has_been_acknowledged);
		sd_kv_int(&wb, "acknowledgement_type", temp_host->acknowledgement_type);
		sd_kv_uint(&wb, "acknowledgement_end_time", temp_host->acknowledgement_end_time);
		sd_kv_int(&wb, "active_checks_enabled", temp_host->checks_enabled);
		sd_kv_int(&wb, "passive_checks_enabled", temp_host->accept_passive_checks);
		sd_kv_int(&wb, "event_handler_enabled", temp_host->event_handler_enabled);
		sd_kv_int(&wb, "flap_detection_enabled", temp_host->flap_detection_enabled);
		sd_kv_int(&wb, "process_performance_data", temp_host->process_performance_data);
		sd_kv_int(&wb, "obsess", temp_host->obsess);
		sd_kv_int(&wb, "is_flapping", temp_host->is_flapping);
		sd_kv_dbl(&wb, "percent_state_change", "%.2f", temp_host->percent_state_change);
		sd_kv_int(&wb, "scheduled_downtime_depth", temp_host->scheduled_downtime_depth);
		sd_kv_str(&wb, "last_update", tv_str(&temp_host->last_update));
		/* custom variables */
		for (temp_customvariablesmember = temp_host->custom_variables; temp_customvariablesmember != NULL; temp_customvariablesmember = temp_customvariablesmember->next) {
			if (temp_customvariablesmember->variable_name)
				nm_wb_customvar(&wb, "\t", temp_customvariablesmember);
		}
		nm_wb_lit(&wb, "\t}\n\n");
	}

	/* save service status data */
	for (temp_service = service_list; temp_service != NULL; temp_service = temp_service->next) {

		nm_wb_lit(&wb, "servicestatus {\n");
		sd_kv_str(&wb, "host_name", temp_service->host_name);

		sd_kv_str(&wb, "service_description", temp_service->description);
		sd_kv_uint(&wb, "modified_attributes", temp_service->modified_attributes);
		sd_kv_str(&wb, "check_command", temp_service->check_command);
		sd_kv_str(&wb, "check_period", temp_service->check_period);
		sd_kv_str(&wb, "notification_period", temp_service->notification_period);
		sd_kv_dbl(&wb, "check_interval", "%f", temp_service->check_interval);
		sd_kv_dbl(&wb, "retry_interval", "%f", temp_service->retry_interval);
		sd_kv_str(&wb, "event_handler", temp_service->event_handler);

		sd_kv_int(&wb, "has_been_checked", temp_service->has_been_checked);
		sd_kv_dbl(&wb, "check_execution_time", "%.3f", temp_service->execution_time);
		sd_kv_dbl(&wb, "check_latency", "%.3f", temp_service->latency);
		sd_kv_int(&wb, "check_type", temp_service->check_type);
		sd_kv_int(&wb, "current_state", temp_service->current_state);
		sd_kv_int(&wb, "last_hard_state", temp_service->last_hard_state);
		sd_kv_uint(&wb, "last_event_id", temp_service->last_event_id);
		sd_kv_uint(&wb, "current_event_id", temp_service->current_event_id);
		sd_kv_str(&wb, "current_problem_id", temp_service->current_problem_id);
		sd_kv_str(&wb, "last_problem_id", temp_service->last_problem_id);
		sd_kv_uint(&wb, "problem_start", temp_service->problem_start);
		sd_kv_uint(&wb, "problem_end", temp_service->problem_end);
		sd_kv_int(&wb, "current_attempt", temp_service->current_attempt);
		sd_kv_int(&wb, "max_attempts", temp_service->max_attempts);
		sd_kv_int(&wb, "state_type", temp_service->state_type);
		sd_kv_uint(&wb, "last_state_change", temp_service->last_state_change);
		sd_kv_uint(&wb, "last_hard_state_change", temp_service->last_hard_state_change);
		sd_kv_uint(&wb, "last_time_ok", temp_service->last_time_ok);
		sd_kv_uint(&wb, "last_time_warning", temp_service->last_time_warning);
		sd_kv_uint(&wb, "last_time_unknown", temp_service->last_time_unknown);
		sd_kv_uint(&wb, "last_time_critical", temp_service->last_time_critical);
		sd_kv_str(&wb, "plugin_output", temp_service->plugin_output);
		sd_kv_str(&wb, "long_plugin_output", temp_service->long_plugin_output);
		sd_kv_str(&wb, "performance_data", temp_service->perf_data);
		sd_kv_uint(&wb, "last_check", temp_service->last_check);
		sd_kv_uint(&wb, "next_check", temp_service->next_check);
		sd_kv_int(&wb, "check_options", temp_service->check_options);
		sd_kv_int(&wb, "current_notification_number", temp_service->current_notification_number);
		sd_kv_str(&wb, "current_notification_id", temp_service->current_notification_id);
		sd_kv_uint(&wb, "last_notification", temp_service->last_notification);
		sd_kv_uint(&wb, "next_notification", temp_service->next_notification);
		sd_kv_int(&wb, "no_more_notifications", temp_service->no_more_notifications);
		sd_kv_int(&wb, "notifications_enabled", temp_service->notifications_enabled);
		sd_kv_int(&wb, "active_checks_enabled", temp_service->checks_enabled);
		sd_kv_int(&wb, "passive_checks_enabled", temp_service->accept_passive_checks);
		sd_kv_int(&wb, "event_handler_enabled", temp_service->event_handler_enabled);
		sd_kv_int(&wb, "problem_has_been_acknowledged", temp_service->problem_has_been_acknowledged);
		sd_kv_int(&wb, "acknowledgement_type", temp_service->acknowledgement_type);
		sd_kv_uint(&wb, "acknowledgement_end_time", temp_service->acknowledgement_end_time);
		sd_kv_int(&wb, "flap_detection_enabled", temp_service->flap_detection_enabled);
		sd_kv_int(&wb, "process_performance_data", temp_service->process_performance_data);
		sd_kv_int(&wb, "obsess", temp_service->obsess);
		sd_kv_int(&wb, "is_flapping", temp_service->is_flapping);
		sd_kv_dbl(&wb, "percent_state_change", "%.2f", temp_service->percent_state_change);
		sd_kv_int(&wb, "scheduled_downtime_depth", temp_service->scheduled_downtime_depth);
		sd_kv_str(&wb, "last_update", tv_str(&temp_service->last_update));
		/* custom variables */
		for (temp_customvariablesmember = temp_service->custom_variables; temp_customvariablesmember != NULL; temp_customvariablesmember = temp_customvariablesmember->next) {
			if (temp_customvariablesmember->variable_name)
				nm_wb_customvar(&wb, "\t", temp_customvariablesmember);
		}
		nm_wb_lit(&wb, "\t}\n\n");
	}

	/* save contact status data */
	for (temp_contact = contact_list; temp_contact != NULL; temp_contact = temp_contact->next) {

		nm_wb_lit(&wb, "contactstatus {\n");
		sd_kv_str(&wb, "contact_name", temp_contact->name);

		sd_kv_uint(&wb, "modified_attributes", temp_contact->modified_attributes);
		sd_kv_uint(&wb, "modified_host_attributes", temp_contact->modified_host_attributes);
		sd_kv_uint(&wb, "modified_service_attributes", temp_contact->modified_service_attributes);
		sd_kv_str(&wb, "host_notification_period", temp_contact->host_notification_period);
		sd_kv_str(&wb, "service_notification_period", temp_contact->service_notification_period);

		sd_kv_uint(&wb, "last_host_notification", temp_contact->last_host_notification);
		sd_kv_uint(&wb, "last_service_notification", temp_contact->last_service_notification);
		sd_kv_int(&wb, "host_notifications_enabled", temp_contact->host_notifications_enabled);
		sd_kv_int(&wb, "service_notifications_enabled", temp_contact->service_notifications_enabled);
		/* custom variables */
		for (temp_customvariablesmember = temp_contact->custom_variables; temp_customvariablesmember != NULL; temp_customvariablesmember = temp_customvariablesmember->next) {
			if (temp_customvariablesmember->variable_name)
				nm_wb_customvar(&wb, "\t", temp_customvariablesmember);
		}
		nm_wb_lit(&wb, "\t}\n\n");
	}

	/* save all comments */
	if(comment_hashtable != NULL) {
		g_hash_table_iter_init(&iter, comment_hashtable);
		while (g_hash_table_iter_next(&iter, NULL, &comment_)) {
			temp_comment = comment_;
			if (temp_comment->comment_type == HOST_COMMENT)
				nm_wb_lit(&wb, "hostcomment {\n");
			else
				nm_wb_lit(&wb, "servicecomment {\n");
			sd_kv_str(&wb, "host_name", temp_comment->host_name);
			if (temp_comment->comment_type == SERVICE_COMMENT)
				sd_kv_str(&wb, "service_description", temp_comment->service_description);
			sd_kv_int(&wb, "entry_type", temp_comment->entry_type);
			sd_kv_uint(&wb, "comment_id", temp_comment->comment_id);
			sd_kv_int(&wb, "source", temp_comment->source);
			sd_kv_int(&wb, "persistent", temp_comment->persistent);
			sd_kv_uint(&wb, "entry_time", temp_comment->entry_time);
			sd_kv_int(&wb, "expires", temp_comment->expires);
			sd_kv_uint(&wb, "expire_time", temp_comment->expire_time);
			sd_kv_str(&wb, "author", temp_comment->author);
			sd_kv_str(&wb, "comment_data", temp_comment->comment_data);
			nm_wb_lit(&wb, "\t}\n\n");
		}
	}

	/* save all downtime */
	for (temp_downtime = scheduled_downtime_list; temp_downtime != NULL; temp_downtime = temp_downtime->next) {

		if (temp_downtime->type == HOST_DOWNTIME)
			nm_wb_lit(&wb, "hostdowntime {\n");
		else
			nm_wb_lit(&wb, "servicedowntime {\n");
		sd_kv_str(&wb, "host_name", temp_downtime->host_name);
		if (temp_downtime->type == SERVICE_DOWNTIME)
			sd_kv_str(&wb, "service_description", temp_downtime->service_description);
		sd_kv_uint(&wb, "downtime_id", temp_downtime->downtime_id);
		sd_kv_uint(&wb, "comment_id", temp_downtime->comment_id);
		sd_kv_uint(&wb, "entry_time", temp_downtime->entry_time);
		sd_kv_uint(&wb, "start_time", temp_downtime->start_time);
		sd_kv_uint(&wb, "flex_downtime_start", temp_downtime->flex_downtime_start);
		sd_kv_uint(&wb, "end_time", temp_downtime->end_time);
		sd_kv_uint(&wb, "triggered_by", temp_downtime->triggered_by);
		sd_kv_int(&wb, "fixed", temp_downtime->fixed);
		sd_kv_uint(&wb, "duration", temp_downtime->duration);
		sd_kv_int(&wb, "is_in_effect", temp_downtime->is_in_effect);
		sd_kv_int(&wb, "start_notification_sent", temp_downtime->start_notification_sent);
		sd_kv_str(&wb, "author", temp_downtime->author);
		sd_kv_str(&wb, "comment", temp_downtime->comment);
		nm_wb_lit(&wb, "\t}\n\n");
	}


	/* flush the remaining buffer to disk */
	result = nm_writebuf_done(&wb);

	/* reset file permissions */
	fchmod(fd, S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH);

	/* fsync the file so that it is completely written out before moving it */
	fsync(fd);

	/* close the temp file */
	result |= close(fd);

	/* save/close was successful */
	if (result == 0) {

		result = OK;

		/* move the temp file to the status log (overwrite the old status log) */
		if (my_rename(tmp_log, status_file)) {
			unlink(tmp_log);
			nm_log(NSLOG_RUNTIME_ERROR, "Error: Unable to update status data file '%s': %s", status_file, strerror(errno));
			result = ERROR;
		}
	}

	/* a problem occurred saving the file */
	else {

		result = ERROR;

		/* remove temp file and log an error */
		unlink(tmp_log);
		nm_log(NSLOG_RUNTIME_ERROR, "Error: Unable to save status file: %s", strerror(errno));
	}

	nm_free(tmp_log);

	return result;
}
