name: citest

on:
  push:
  pull_request:
  release:

jobs:
  citest:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: optimized
            cflags: "-O2"
          - name: debug
            cflags: "-g -O0"
          - name: address-sanitizer
            cflags: "-g -O0 -fsanitize=address -fno-omit-frame-pointer"
    name: CI (${{ matrix.name }})
    steps:
      - uses: actions/checkout@main
      #- name: Setup tmate session, see https://github.com/marketplace/actions/debugging-with-tmate
      #  uses: mxschmitt/action-tmate@v3
      - name: prepare machine
        run: |
          sudo apt-get update
          sudo apt-get install \
              autoconf \
              build-essential \
              libasan8 \
              libglib2.0-dev \
              gperf \
              check \
              help2man \
              python3-pip \
              flake8 \
              python3-behave

      - name: run build
        run: |
          CFLAGS='${{ matrix.cflags }}' ./autogen.sh
          make

      - name: run tests
        run: |
          make check VERBOSE=1
          make distcheck
          flake8 features/
          behave
